// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolunteerMS.Data;

#nullable disable

namespace VolunteerMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VolunteerMS.Models.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Centers", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CenterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteersNeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Opportunities", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Availability")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DriverLicenseOnFile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationalBackground")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Licenses")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SSCardOnFile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Volunteers", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.VolunteerCenter", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CenterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VolunteerId", "CenterId");

                    b.HasIndex("CenterId");

                    b.ToTable("VolunteerCenters", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.VolunteerOpportunity", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateMatched")
                        .HasColumnType("TEXT");

                    b.HasKey("VolunteerId", "OpportunityId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("VolunteerOpportunities", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.VolunteerSkill", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VolunteerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("VolunteerSkills", (string)null);
                });

            modelBuilder.Entity("VolunteerMS.Models.Opportunity", b =>
                {
                    b.HasOne("VolunteerMS.Models.Center", "Center")
                        .WithMany("Opportunities")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("VolunteerMS.Models.Volunteer", b =>
                {
                    b.HasOne("VolunteerMS.Models.User", "User")
                        .WithOne("Volunteer")
                        .HasForeignKey("VolunteerMS.Models.Volunteer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolunteerMS.Models.VolunteerCenter", b =>
                {
                    b.HasOne("VolunteerMS.Models.Center", "Center")
                        .WithMany("VolunteerCenters")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerMS.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerCenters")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMS.Models.VolunteerOpportunity", b =>
                {
                    b.HasOne("VolunteerMS.Models.Opportunity", "Opportunity")
                        .WithMany("VolunteerOpportunities")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerMS.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerOpportunities")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMS.Models.VolunteerSkill", b =>
                {
                    b.HasOne("VolunteerMS.Models.Skill", "Skill")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerMS.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMS.Models.Center", b =>
                {
                    b.Navigation("Opportunities");

                    b.Navigation("VolunteerCenters");
                });

            modelBuilder.Entity("VolunteerMS.Models.Opportunity", b =>
                {
                    b.Navigation("VolunteerOpportunities");
                });

            modelBuilder.Entity("VolunteerMS.Models.Skill", b =>
                {
                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("VolunteerMS.Models.User", b =>
                {
                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMS.Models.Volunteer", b =>
                {
                    b.Navigation("VolunteerCenters");

                    b.Navigation("VolunteerOpportunities");

                    b.Navigation("VolunteerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
